---
language: node_js
node_js:
  - "6.9.1"

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  ssh_known_hosts: 89.146.10.221

cache:
  directories:
    - node_modules

branches:
  only:
    - master

env:
  - EMBER_TRY_SCENARIO=ember-lts-2.16
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g npm@^4"
  - "npm install -g bower"

install:
  - npm install --no-optional
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test
